# Generated by Django 3.2.4 on 2021-06-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notepad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('dt_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
